services:
  app:
    image: isakin/emogi-dev:latest
    container_name: emogi-app-2
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - ${PROJECT_PATH}/.env.dev:/app/.env.dev
      - ~/.aws:/root/.aws
    ports:
      - "8200:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - emogi-network

  db:
    image: postgres:16.4-bullseye
    container_name: emogi-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 7
      start_period: 5s
    expose:
      - "5432"
    ports:
      - "8201:5432"
    volumes:
      - emogi-data:/var/lib/postgresql/data
    networks:
      - emogi-network

networks:
  emogi-network:
    driver: bridge

volumes:
  emogi-data: