services:
  app:
    image: isakin/emogi-app:latest
    container_name: emogi-app-2
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ${PROJECT_PATH}/.env.app:/app/.env
      - ~/.aws:/root/.aws
    ports:
      - "${SERVER_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - emogi-network

  db:
    image: postgres:16.4-bullseye
    container_name: emogi-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    expose:
      - "5432"
    volumes:
      - emogi-data:/var/lib/postgresql/data
    networks:
      - emogi-network

networks:
  emogi-network:
    driver: bridge

volumes:
  emogi-data: