"""add name in chats and time data

Revision ID: 07e73a8835c2
Revises: fbe3bdda4e8e
Create Date: 2025-03-16 18:21:43.993240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07e73a8835c2'
down_revision: Union[str, None] = 'fbe3bdda4e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('chats', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('chats', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('chats', 'chat_create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('chat_create_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('chats', 'updated_at')
    op.drop_column('chats', 'created_at')
    op.drop_column('chats', 'name')
    # ### end Alembic commands ###
