"""Initial migration

Revision ID: 7eb63797855d
Revises: 
Create Date: 2025-01-06 19:15:49.554382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb63797855d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('model_name', sa.String(length=255), nullable=True))
    op.add_column('chat_logs', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_logs', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_logs', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_logs', sa.Column('token_cost', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_logs', 'token_cost')
    op.drop_column('chat_logs', 'total_tokens')
    op.drop_column('chat_logs', 'completion_tokens')
    op.drop_column('chat_logs', 'prompt_tokens')
    op.drop_column('chat_logs', 'model_name')
    # ### end Alembic commands ###
