"""autogenerate

Revision ID: 9de5b77c2e92
Revises: 5270fa094859
Create Date: 2025-01-06 22:23:33.397299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de5b77c2e92'
down_revision: Union[str, None] = '5270fa094859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_logs', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_logs', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_logs', sa.Column('token_cost', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_logs', 'token_cost')
    op.drop_column('chat_logs', 'total_tokens')
    op.drop_column('chat_logs', 'completion_tokens')
    op.drop_column('chat_logs', 'prompt_tokens')
    # ### end Alembic commands ###
