"""add feedback/user relationship

Revision ID: fbe3bdda4e8e
Revises: fcff22e269a7
Create Date: 2025-01-07 17:13:24.573318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe3bdda4e8e'
down_revision: Union[str, None] = 'fcff22e269a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('feedback_image_key', sa.String(length=500), nullable=True))
    op.drop_column('feedbacks', 'feedback_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('feedback_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('feedbacks', 'feedback_image_key')
    # ### end Alembic commands ###
