"""add feedback table

Revision ID: fcff22e269a7
Revises: 9de5b77c2e92
Create Date: 2025-01-07 16:34:41.828879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcff22e269a7'
down_revision: Union[str, None] = '9de5b77c2e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('feedback_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('feedback_type', sa.Enum('BUG', 'FEATURE', 'IMPROVEMENT', 'OTHER', name='feedbacktype'), nullable=False),
    sa.Column('feedback_title', sa.String(length=255), nullable=False),
    sa.Column('feedback_content', sa.Text(), nullable=True),
    sa.Column('feedback_image_url', sa.String(length=500), nullable=True),
    sa.Column('feedback_device_info', sa.String(length=255), nullable=False),
    sa.Column('feedback_app_version', sa.String(length=255), nullable=False),
    sa.Column('feedback_status', sa.Enum('RECEIVED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='feedbackstatus'), nullable=False),
    sa.Column('feedback_create_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('feedback_admin_comment', sa.Text(), nullable=True),
    sa.Column('feedback_resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
